app:
  greet: Hello World
my:
  list:
    values: one,two,three
dbValues: "{ username:'foo', password:'bar'}"


db:
  host: localhost
  port: 9042
  username: foo
  password: bar

management.endpoints.web.exposure.include: "*"

spring.profiles.active: test
spring.clould.config.uri: http://localhost:8888